# Generated by Django 4.2.4 on 2024-02-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0006_alter_cartorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(choices=[(1, ' ⭐☆☆☆☆'), (2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆'), (5, '⭐⭐⭐⭐⭐')], default=None),
        ),
    ]
