# Generated by Django 4.2.4 on 2024-02-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0007_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
