# Generated by Django 4.2.4 on 2024-02-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0008_remove_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=9),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=9),
        ),
    ]
