# Generated by Django 4.2.4 on 2024-03-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0013_color_size_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
