# Generated by Django 4.2.4 on 2024-03-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0014_cartorder_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rarechild.product'),
            preserve_default=False,
        ),
    ]
