# Generated by Django 4.2.4 on 2024-03-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0015_cartorderitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rarechild.product'),
        ),
    ]
