# Generated by Django 4.2.4 on 2024-03-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0016_alter_cartorderitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
