# Generated by Django 4.2.4 on 2024-03-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0017_cartorderitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cart-images'),
        ),
    ]
