# Generated by Django 4.2.4 on 2024-03-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0018_alter_cartorderitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'delivered')], default='active', max_length=50),
        ),
    ]
