# Generated by Django 4.2.4 on 2024-03-06 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0019_cartorder_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rarechild.cartorder'),
        ),
    ]
