# Generated by Django 4.2.4 on 2024-03-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0020_alter_cartorderitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
