# Generated by Django 4.2.4 on 2024-03-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rarechild', '0021_cartorderitems_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
